remove_order_payment:
  path: removeorderpayment/delete
  methods: [DELETE]
  defaults:
    _controller: 'PrestaShop\Module\RemoveOrderPayment\Controller\Admin\RemovePaymentController::deleteAction'
    _legacy_controller: RemoveOrderPayment
    _legacy_link: RemoveOrderPayment
