hmedia_remove_order_payment:
  path: removeorderpayment/delete
  methods: [ DELETE ]
  defaults:
    _controller: 'HMedia\RemoveOrderPayment\Controllers\Admin\RemovePaymentController::deleteAction'
    _legacy_controller: HMediaRemoveOrderPayment
    _legacy_link: HMediaRemoveOrderPayment

