services:
  _defaults:
    public: true

  order_payment.repository:
    class: PrestaShop\Module\RemoveOrderPayment\Entity\Repository\OrderPaymentRepository
    arguments:
      - "@doctrine.dbal.default_connection"
      - "%database_prefix%"

  PrestaShop\Module\RemoveOrderPayment\Controller\Admin\RemovePaymentController:
    arguments:
      - "@order_payment.repository"
